apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: tailmates
data:
  tailmatesdb.sql: |
    -- phpMyAdmin SQL Dump
    -- version 5.2.1
    -- https://www.phpmyadmin.net/
    --
    -- Host: 127.0.0.1
    -- Generation Time: May 12, 2026 at 04:50 PM
    -- Server version: 10.4.32-MariaDB
    -- PHP Version: 8.2.12

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";


    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;

    --
    -- Database: `tailmatesdb`
    --

    -- --------------------------------------------------------

    --
    -- Table structure for table `pet_profile`
    --

    CREATE TABLE `pet_profile` (
      `pet_id` int(11) NOT NULL,
      `user_id` int(11) DEFAULT NULL,
      `pet_name` varchar(50) NOT NULL,
      `age` varchar(20) DEFAULT 'Unknown',
      `type` varchar(25) NOT NULL,
      `gender` enum('male','female') NOT NULL,
      `breed` varchar(50) DEFAULT NULL,
      `pet_image` varchar(255) NOT NULL DEFAULT 'No Picture Uploaded',
      `pet_desc` text NOT NULL,
      `status` enum('For rehoming','For adoption','Adopted','Deceased') NOT NULL DEFAULT 'For rehoming',
      `reason` text NOT NULL,
      `created` timestamp NOT NULL DEFAULT current_timestamp(),
      `updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- --------------------------------------------------------

    --
    -- Table structure for table `transactions`
    --

    CREATE TABLE `transactions` (
      `trans_id` int(11) NOT NULL,
      `user_id` int(11) DEFAULT NULL,
      `pet_id` int(11) DEFAULT NULL,
      `trans_type` varchar(75) DEFAULT NULL,
      `trans_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
      `trans_details` varchar(255) DEFAULT NULL,
      `category` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- --------------------------------------------------------

    --
    -- Table structure for table `users`
    --

    CREATE TABLE `users` (
      `user_id` int(11) NOT NULL,
      `user_name` varchar(50) NOT NULL,
      `user_email` varchar(75) NOT NULL,
      `user_password` char(255) NOT NULL,
      `role` enum('user','admin') DEFAULT 'user',
      `register_date` datetime DEFAULT current_timestamp(),
      `last_login` timestamp NULL DEFAULT current_timestamp()
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `users`
    --

    INSERT INTO `users` (`user_id`, `user_name`, `user_email`, `user_password`, `role`, `register_date`, `last_login`) VALUES
    (1, 'admin', 'admin@gmail.com', 'adminPass', 'admin', '2026-05-12 00:22:13', '2026-05-12 14:08:46');

    --
    -- Indexes for dumped tables
    --

    --
    -- Indexes for table `pet_profile`
    --
    ALTER TABLE `pet_profile`
      ADD PRIMARY KEY (`pet_id`),
      ADD KEY `pet_profile_ibfk_1` (`user_id`);

    --
    -- Indexes for table `transactions`
    --
    ALTER TABLE `transactions`
      ADD PRIMARY KEY (`trans_id`),
      ADD KEY `user_id` (`user_id`),
      ADD KEY `pet_id` (`pet_id`);

    --
    -- Indexes for table `users`
    --
    ALTER TABLE `users`
      ADD PRIMARY KEY (`user_id`),
      ADD UNIQUE KEY `user_email` (`user_email`);

    --
    -- AUTO_INCREMENT for dumped tables
    --

    --
    -- AUTO_INCREMENT for table `pet_profile`
    --
    ALTER TABLE `pet_profile`
      MODIFY `pet_id` int(11) NOT NULL AUTO_INCREMENT;

    --
    -- AUTO_INCREMENT for table `transactions`
    --
    ALTER TABLE `transactions`
      MODIFY `trans_id` int(11) NOT NULL AUTO_INCREMENT;

    --
    -- AUTO_INCREMENT for table `users`
    --
    ALTER TABLE `users`
      MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

    --
    -- Constraints for dumped tables
    --

    --
    -- Constraints for table `pet_profile`
    --
    ALTER TABLE `pet_profile`
      ADD CONSTRAINT `pet_profile_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE;

    --
    -- Constraints for table `transactions`
    --
    ALTER TABLE `transactions`
      ADD CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE SET NULL,
      ADD CONSTRAINT `transactions_ibfk_2` FOREIGN KEY (`pet_id`) REFERENCES `pet_profile` (`pet_id`) ON DELETE SET NULL;
    COMMIT;

    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;